/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API仕様サンプル
 * API仕様サンプルです
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { UsersDTO, ShowUsersParams, UserDTO } from '.././schemas';

/**
 * 指定された検索条件に一致するユーザーを取得します。
 * @summary ユーザー情報一覧の取得
 */
export const showUsers = <TData = AxiosResponse<UsersDTO>>(
  params?: ShowUsersParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/users`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
/**
 * 指定されたIDのユーザー情報を取得します。
 * @summary ユーザー情報の取得
 */
export const showUserById = <TData = AxiosResponse<UserDTO>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/users/${id}`, options);
};
export type ShowUsersResult = AxiosResponse<UsersDTO>;
export type ShowUserByIdResult = AxiosResponse<UserDTO>;
