/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API仕様サンプル
 * API仕様サンプルです
 * OpenAPI spec version: 1.0.0
 */

/**
 * 汎用エラーレスポンス
 */
export interface CommonErrorDTO {
  /** ステータスコード */
  code: number;
  /** エラーメッセージ */
  message: string;
}
