/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API仕様サンプル
 * API仕様サンプルです
 * OpenAPI spec version: 1.0.0
 */
import type { UserNameParams } from './userNameParams';

export type ShowUsersParams = {
  user_name?: UserNameParams;
};
