/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API仕様サンプル
 * API仕様サンプルです
 * OpenAPI spec version: 1.0.0
 */

/**
 * 権限
 */
export type UserDTORole = (typeof UserDTORole)[keyof typeof UserDTORole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDTORole = {
  Admin: 'Admin',
  Member: 'Member',
} as const;
