/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API仕様サンプル
 * API仕様サンプルです
 * OpenAPI spec version: 1.0.0
 */
import type { UserDTO } from './userDTO';

/**
 * ユーザー情報
 */
export interface UsersDTO {
  /** ユーザー一覧 */
  users: UserDTO[];
}
