/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * API仕様サンプル
 * API仕様サンプルです
 * OpenAPI spec version: 1.0.0
 */
import type { UserDTORole } from './userDTORole';

/**
 * ユーザー情報
 */
export interface UserDTO {
  /** 住所 */
  address: string;
  /** 名前 */
  name: string;
  /** メールアドレス */
  email: string;
  /** 電話番号 */
  tel: string;
  /** 権限 */
  role: UserDTORole;
}
